VilledeMontreal/workit

.commitlintrc.yml, .npmrc.template, .travis.yml, lerna.json, package-lock.json, package.json, packages/workit-camunda/.commitlintrc.yml, packages/workit-camunda/__tests__/workit-camunda.test.js, packages/workit-camunda/package-lock.json, packages/workit-camunda/package.json, packages/workit-cli/.commitlintrc.yml, packages/workit-cli/__tests__/workit-cli.test.js, packages/workit-cli/package-lock.json, packages/workit-cli/tests/test.spec.ts
chore: improve commitlint file
fix(workit-cli): npm run test
closes #
=> ci(travis): add config file

.travis.yml
=> ci(travis): should fix lerna publish

.travis.yml, packages/workit-camunda/package.json
=> chore(codecoverage): add codecoverage

packages/workit-camunda/src/models/camunda-n-mq/specs/workflowClient.ts, packages/workit-camunda/src/models/zeebe/specs/payload.ts, packages/workit-camunda/src/models/zeebe/zeebeClient.ts, packages/workit-camunda/src/models/zeebe/zeebeMapperProperties.ts, packages/workit-camunda/src/models/zeebe/zeebeMessage.ts, packages/workit-camunda/src/tests/functionals/__snapshots__/zeebe.spec.ts.snap, packages/workit-camunda/src/tests/functionals/zeebe.spec.ts, packages/workit-cli/package.json
=> feat: improve generic types for Zeebe

packages/workit-cli/package-lock.json, packages/workit-cli/src/command/create/task/index.ts, packages/workit-cli/src/index.ts
=> fix: remove console.log

CHANGELOG.md, packages/workit-cli/src/command/init/templates/node/default/src/package.json
=> feat(worker-cli): update deps and init template

CHANGELOG.md
=> docs(workit-cli): update CHANGELOG

.gitignore, CHANGELOG.md, lerna.json
=> chore: improve changelog (use lerna-changelog)

README.md
=> docs(readme): minor spelling fix

packages/workit-camunda/package-lock.json, packages/workit-camunda/package.json, packages/workit-camunda/src/models/zeebe/specs/payload.ts, packages/workit-camunda/src/models/zeebe/zeebeMapperProperties.ts, packages/workit-camunda/src/models/zeebe/zeebeMessage.ts, packages/workit-camunda/src/tests/functionals/__snapshots__/zeebeMessage.spec.ts.snap, packages/workit-camunda/src/tests/functionals/zeebeMessage.spec.ts
- variables field issue (since update to zeebe-node 2.3.0)
- add test (in order to avoid regression)
closes #
=> fix(workit-camunda): regression from zeebe-node 2.3.0

README.md, README_FR.md
Signed-off-by: jperron-ca <jessieperron@gmail.com>
closes #35
=> docs(readme): #35 add version matrix

CHANGELOG.md, README.md, README_FR.md, docker/README.md, packages/workit-camunda/CHANGELOG.md, packages/workit-camunda/README.md, packages/workit-camunda/package-lock.json, packages/workit-camunda/package.json, packages/workit-camunda/src/models/camunda/camundaMessage.ts, packages/workit-camunda/src/models/zeebe/zeebeClient.ts, packages/workit-camunda/src/models/zeebe/zeebeMessage.ts, packages/workit-camunda/src/tests/functionals/__snapshots__/camundaMessage.spec.ts.snap, packages/workit-camunda/src/tests/functionals/camundaMessage.spec.ts, packages/workit-cli/CHANGELOG.md, packages/workit-cli/README.md, packages/workit-cli/src/command/init/templates/node/default/src/package.json, packages/zeebe-elasticsearch-client/CHANGELOG.md
=> feat(zeebe): add 0.20.0 compatibility

packages/workit-camunda/.docs/WORKER.md
Signed-off-by: dmousseau <dominicmousseau@gmail.com>
closes #
=> docs: improving getting started documentation

.circleci/config.yml
=> chore: remove working_dir step in circleci config file

packages/workit-camunda/src/models/core/processHandler/simpleCamundaProcessHandler.ts, packages/workit-camunda/src/tests/data/bpmn/zeebe/msg-start-simple.bpmn, packages/workit-camunda/src/tests/data/bpmn/zeebe/msg-start.bpmn, packages/workit-camunda/src/tests/integrations/zeebe.spec.ts
=> test(zeebe): increase coverage and fix related code

README.md, README_FR.md
=> docs: fix broken links (fr/en)

package.json, packages/workit-camunda/package.json, packages/workit-cli/package.json, packages/workit-cli/src/command/init/templates/node/default/src/package.json
=> Greenkeeper/default/@types/node 12.7.3

packages/workit-bpm-client/package.json, packages/workit-bpm-client/src/camundaBpmClient.ts, packages/workit-bpm-client/src/camundaMapperProperties.ts, packages/workit-bpm-client/src/camundaMessage.ts, packages/workit-bpm-client/src/repositories/camundaRepository.ts, packages/workit-bpm-client/src/utils/paginationUtils.ts, packages/workit-bpm-client/tslint.json, packages/workit-camunda/package.json, packages/workit-camunda/src/camunda-n-mq/client.ts, packages/workit-camunda/tslint.json, packages/workit-cli/package.json, packages/workit-cli/tslint.json, packages/workit-cli/yarn.lock, packages/workit-core/package.json, packages/workit-core/src/IoC.ts, packages/workit-core/src/interceptors.ts, packages/workit-core/src/opentelemetry/jaeger/simpleFormat.ts, packages/workit-core/src/proxyObserver.ts, packages/workit-core/tslint.json, packages/workit-types/package.json, packages/workit-types/tslint.json, packages/workit-zeebe-client/package.json, packages/workit-zeebe-client/src/utils/paginationUtils.ts, packages/workit-zeebe-client/src/zeebeClient.ts, packages/workit-zeebe-client/tslint.json, packages/zeebe-elasticsearch-client/package.json, packages/zeebe-elasticsearch-client/src/repositories/zbElasticClient.ts, packages/zeebe-elasticsearch-client/tslint.json, packages/zeebe-elasticsearch-client/yarn.lock, tslint.base.js
=> chore: set explicit naming conventions

examples/opentelemetry/package.json, examples/opentelemetry/src/worker.ts, package.json, packages/workit-bpm-client/package.json, packages/workit-camunda/package.json, packages/workit-core/package.json, packages/workit-types/package.json, packages/workit-zeebe-client/package.json
closes #123 
closes #124 
closes #125 
closes #126 
closes #127 
closes #128
=> feat(opentelemetry): make it compatible with 0.3.3

examples/failure-strategy/CHANGELOG.md, examples/failure-strategy/LICENSE, examples/failure-strategy/bpmn/BPMN_DEMO.bpmn, examples/failure-strategy/package.json, examples/failure-strategy/prettier.config.js, examples/failure-strategy/src/create-process-instances.ts, examples/failure-strategy/src/deploy.ts, examples/failure-strategy/src/failure-strategy.ts, examples/failure-strategy/src/worker.ts, examples/failure-strategy/tasks/helloWorldTask.ts, examples/failure-strategy/tsconfig.json, examples/failure-strategy/tslint.json, packages/workit-bpm-client/src/camundaMapperProperties.ts
closes #130 
Still need to expose bpmn error handler through ICamundaService since Zeebe add it recently!
https://github.com/creditsenseau/zeebe-client-node-js/blob/master/CHANGELOG.md#version-0221
=> docs: add bpmnError example

packages/workit-bpm-client/package.json, packages/workit-bpm-client/src/bpmClient.ts, packages/workit-bpm-client/src/bpmLogger.ts, packages/workit-bpm-client/src/index.ts, packages/workit-camunda/package.json, packages/workit-camunda/src/config/container.ts, packages/workit-camunda/src/config/ioc.ts, packages/workit-camunda/tests/functionals/camunda.spec.ts, packages/workit-camunda/tests/functionals/camundaManager.spec.ts, packages/workit-camunda/types/camunda-external-task-client-js.d.ts
=> fix: remove camunda-xx-client-js in workit-camunda

.circleci/checksum.sh, .circleci/config.yml, README.md, README_FR.md, codecov.yml, examples/basic/package.json, examples/binding/package.json, examples/event/package.json, examples/failure-strategy/package.json, examples/opentelemetry/package.json, examples/parallel/package.json, greenkeeper.json, package.json, packages/workit-bpm-client/package.json, packages/workit-camunda/package.json, packages/workit-cli/package.json, packages/workit-core/package.json, packages/workit-types/package.json, packages/workit-zeebe-client/package.json, packages/workit-zeebe-client/tests/integrations/zeebe.spec.ts, packages/zeebe-elasticsearch-client/package.json
Fixes #135
Fixes #136
- docs: format tables in readme
- update circleci for cache and codecov
- setup codecov in order to grab all reports for all packages
=> chore: set codecov for all packages

.circleci/config.yml, lerna.json, package.json, packages/workit-camunda/package.json, packages/workit-camunda/tests/integrations/zeebe.spec.ts, packages/workit-zeebe-client/tests/integrations/zeebe.spec.ts
- Change lerna setting for managing one version for all packages
=> ci(lerna): manage one version for all packages

CHANGELOG.md
=> docs(changelog): correct changes for 4.1.0

packages/zeebe-elasticsearch-client/package.json, packages/zeebe-elasticsearch-client/src/specs/headers.ts, packages/zeebe-elasticsearch-client/yarn.lock
=> ci(zeebe-elasticsearch-client): update axios

.circleci/config.yml, package-lock.json, package.json, packages/workit-bpm-client/package-lock.json, packages/workit-bpm-client/package.json, packages/workit-core/package-lock.json, packages/workit-core/package.json, packages/workit-stepfunction-client/package-lock.json, packages/workit-stepfunction-client/package.json, packages/workit-types/package-lock.json, packages/workit-types/package.json, packages/workit/package-lock.json, packages/workit/package.json
=> fix: lerna issue with package-lock.json
